version: 2.1

jobs:
  deploy_to_heroku:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      - run: |
          cd anecdotes
          docker build -t registry.heroku.com/$HEROKU_APP_NAME/web .
          echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: "Install Heroku CLI, if necessary"
          command: |
            if [[ $(command -v heroku) == "" ]]; then
              curl https://cli-assets.heroku.com/install.sh | sh
            else
              echo "Heroku is already installed. No operation was performed."
            fi

#          - run: echo "$HEROKU_LOGIN" | heroku login

workflows:
  heroku_deploy:
    jobs:
      - deploy_to_heroku
